<a href="https://colab.research.google.com/github/jcandane/PhysicsI_Labs/blob/main/vectorsnarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectors

Import numpy,

In [2]:
import numpy as np

for us vectors are represented by arrays, defined as such:

In [36]:
a_vector = np.array([0.,7.,0.])
b_vector = np.array([1.,-4.,-8.])

u = np.random.rand(3)
v = np.random.rand(3)
w = np.random.rand(3)

## Vector Space Operations/Axioms
(from: https://en.wikipedia.org/wiki/Vector_space)

$u + (v + w) = (u + v) + w$

In [37]:
u + (v + w) == (u + v) + w

array([ True,  True,  True])

$u + v = v + u$

In [38]:
u + v == v + u 

array([ True,  True,  True])

There exists an element $0 \in V$, called the zero vector, such that $v + 0 = v$ for all $v \in V$. 

In [39]:
Ø = np.zeros(3)
v + Ø == v 

array([ True,  True,  True])

For every $\mathbf{v} \in V$, there exists an element $−\mathbf{v} \in V$, called the additive inverse of $\mathbf{v}$, such that $\mathbf{v} + (−\mathbf{v}) = 0$. 

In [40]:
v + -v == Ø

array([ True,  True,  True])

$a(b\mathbf{v}) = (ab)\mathbf{v}$

In [51]:
a = 5.
b = 2.

a * (b * v) == (a*b) * v

array([ True,  True,  True])

$1v = v$, where 1 denotes the multiplicative identity. 

In [52]:
I = np.ones(3)

I * v == v

array([ True,  True,  True])

$a(\mathbf{u} + \mathbf{v}) = a\mathbf{u} + a\mathbf{v} $

In [57]:
np.allclose( a * ( u + v ), a* u + a * v )

True

$ (a + b)\mathbf{v} = a\mathbf{v} + b\mathbf{v} $

In [56]:
np.allclose( (a+b) * v , a*v + b*v )

True

## element-wise

#### element-wise operation: power

In [10]:
b_vector ** 2

array([ 1., 16., 64.])

element-wise operation: times

In [13]:
a_vector * b_vector

array([ 0., 28.,  0.])

element-wise operation: addition (adding vectors):

In [5]:
a_vector + b_vector

array([ 1., 11.,  8.])

element-wise operation: divide

In [58]:
a_vector / b_vector

array([ 0.  , -1.75, -0.  ])

## Unary NumPy Operations (1 input, 1 output)

#### Unary NumPy Operations: Sum

In [15]:
np.sum(b_vector)

-11.0

#### Unary NumPy Operations: Norm

In [16]:
np.linalg.norm(a_vector)

7.0

#### Unary NumPy Operations: Prod

In [17]:
np.prod(b_vector)

32.0

#### Unary NumPy Operations: Cumlative Sum

In [18]:
np.cumsum(b_vector)

array([  1.,  -3., -11.])

## Binary NumPy Operations (2 inputs, 1 output)

Dot-product

In [12]:
print( np.dot( a_vector, b_vector ) )

print( np.sum(a_vector * b_vector ) )  ## sum of element-wise (alt. example for dot product)

28.0


28.0

cross product

In [19]:
np.cross(a_vector, b_vector)

array([-56.,   0.,  -7.])

## "Long" Vectors

These have the same operations as reg. 3-arrays (& matrices)

In [26]:
a_range_of_numbers = np.arange(0., 50., 0.1)
b_range_of_numbers = np.ones(50)

In [59]:
np.sum( b_range_of_numbers )

50.0

## Matrix Operations

In [28]:
A_Matrix = np.ones((10,10))
B_Matrix = np.eye(10)

print(A_Matrix)
print(B_Matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [31]:
print( A_Matrix[0] )
print( A_Matrix[0, :] ) ### : gets the whole slice
print( A_Matrix[0, 2:6] ) ### : gets the whole slice

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1.]


In [32]:
np.sum(A_Matrix)

100.0

Element-Wise Array Product

In [33]:
A_Matrix * B_Matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Matrix Product 

In [34]:
A_Matrix @ B_Matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])